version: '3'

services:
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8086:8081
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: dev
#      ME_CONFIG_BASICAUTH_PASSWORD: dev!
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
#    links:
#      - mongo
#    networks:
#      - mongo-compose-network
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
#    networks:
#      - mongo-compose-network
#networks:
#  mongo-compose-network:
#    driver: bridge
